### ISSUE TITLE
Info box color changes in 0.3

### ISSUE THREAD

**Issue by caemor** [jomaway/typst-admonish#1]
Hi, the info box got much darker in 0.3. Was this an intended change?

v0.2:
![grafik](https://github.com/jomaway/typst-admonish/assets/11088935/aebddc01-4bea-457e-a49a-be01d1128dff)

v0.3:
![grafik](https://github.com/jomaway/typst-admonish/assets/11088935/10b209ed-18ad-4b1c-93b5-20a432c7829d)

Relevant code: 
```
#let info(it) = {
  import "@preview/gentle-clues:0.2.0": info
  info(title: "Hinweis", header-inset: headerinsetem, strong(delta: 150, it))
}
``

**Comment by jomaway** [comment]
Hey @caemor sorry for my late reply. This was not intended this way. I started changing the color handling and default colors but didn't finished before 0.3.0.  Must be slipped through. Anyway i just submitted 0.4.0. I changed some default colors there as well but not that drastically. So info is back to a lighter blue.  Sorry for the inconveniences.  

Anyway i am not a color expert so i just choose some colors which seemed reasonable for me. If someone comes up with an color schema which makes more sense than mine i am willing to change it.
